### PR TITLE
Ja version of UsingThymeleaf 3.0

### PR DESCRIPTION
**Pull request by bufferings**
Hi,

We finished creating Japanese version of UsingThymeleaf 3.0, and I'm sure this would contribute to Japanese people who (will) use Thymeleaf.

We're so glad if you kindly accept this PR.

This time, I worked with MasatoshiTada( https://github.com/MasatoshiTada ), and he agreed with https://github.com/thymeleaf/thymeleaf/blob/3.0-master/CONTRIBUTING.markdown

I hope he can be added to the Thymeleaf team :)

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thanks a lot @bufferings and @MasatoshiTada! And sorry for the important delay in my response. These have been crazy months for me.

I'll be really happy to merge your pull request (and add @MasatoshiTada as a contributor). But please, first I would need a comment agreeing to the contribution guidelines from @MasatoshiTada himself, as these agreements should be done on one's own behalf. Would that be possible?

**Comment by danielfernandez** [comment]
Everything is published now and linked from https://www.thymeleaf.org/documentation.html

@bufferings @MasatoshiTada could you please check that the documents look alright?

Also, @MasatoshiTada, I've added you as a contributor at https://www.thymeleaf.org/team.html :)

Thanks a lot to both!

**Comment by bufferings** [comment]
Looks great! Thank you so much @danielfernandez

**Comment by MasatoshiTada** [comment]
@danielfernandez Thank you for adding me!

**Pull request merged**
