### PR TITLE
Added Japanese translation of usingthymeleaf.md.

### PR DESCRIPTION
**Pull request by bufferings**
After a long time I asked you about Japanese translation, finally I added Japanese translation of usingthymeleaf.md. Please check it.

### CODE REVIEW

**Comment by danielfernandez** [comment]
I've finally been able to organize the `thymeleaf-docs` build system in order to support including user-contributed translations like yours in the process.

Please have a look at these (temporary) files:

   * HTML: http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf_ja.html
   * EPUB: http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf_ja.epub
   * MOBI (Amazon Kindle): http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf_ja.mobi
   * PDF: http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf_ja.pdf

Could you tell me if they look OK to you? Regarding the "Japanese translation contributed by" item, I would need you to tell me the email (non-corporate) you want to appear there --unless you don't want to display an email there--, or if you prefer your name to appear in Japanese script.

Also, I'd be really happy to add you as a contributor to http://www.thymeleaf.org/team.html if you want. For that, please send me an email with the name you want to display there, forum ID (if you have one), Location (*Japan*, I suppose), and email (non-corporate).

Again, thanks so much!

**Comment by bufferings** [comment]
I'm really appreciate your great work and consideration!

About ja files:
- Tables show tags for example: http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf_ja.html#特定の属性に値を設定する
- Is it better to use "-(hyphen)" rather than "_(underscore)" for file name from the viewpoint of URL? If so I'm sorry but please could you change the file name?
- Epub file has errors "Double hyphen within comment”, and I have to work on it. But for now, could you proceed to publish them? I will register an issue about it and will send a pull request later.

About "Japanese translation contributed by":
- I prefer "Mitsuyuki Shiiba" to Japanese script.
- I'm sorry but I don't want to show my email address. Instead, could you please add my twitter url "https://twitter.com/bufferings" if possible? Then I will be able to receive some questions via twitter.

I'm really honored to be added to contributors.
- Name: Mitsuyuki Shiiba
- Forum ID: Mitz
- Location: Japan
- Email: I prefer twitter account as I mentioned above.

Thank you!

**Comment by bufferings** [comment]
Reading #18 , I understood table issue. Thanks.

**Comment by danielfernandez** [comment]
These documents were affected by #18, as you mention. I've fixed it and refreshed the docs.

In the case of internationalized files, actually I think it's more standard to use `_` rather than `-`. So IMHO underscore is fine. Would you prefer hyphen for any specific reasons?

Comments should never contain `--`, because according to the HTML spec that's what actually closes them (the `>` in `-->` is just a container artifact).

Twitter... OK. Or your blog at http://bufferings.hatenablog.com/ if you prefer (one article author uses his blog as reference). And OK for no email at the Team page, of course.

**Comment by bufferings** [comment]
Thanks for the table issue.

I got it. I agree with you. Please use underscore.
The reason I proposed it was just because Google prefer hyphen:
https://support.google.com/webmasters/answer/76329?hl=en

Thank you for the explanation, I understood.

I sometimes change my blog url, so Twitter is better. Thank you.
And if it's not so good to show twitter url on the Team page, please leave it blank.

**Comment by danielfernandez** [comment]
I've updated the docs to show your twitter handle. I'll try to update the site linking to the new docs (plus the team page etc. along the next days).

**Comment by bufferings** [comment]
Thank you so much!

**Comment by bufferings** [comment]
Hi
I've sent #20 and #21. I've finished my tasks, and I will go to bed.
(I generated all docs and felt the system is nice:)

**Comment by bufferings** [comment]
Everything seems to be finished.
I'm looking forward to seeing the Japanese doc published:D
Thank you, guys!

**Comment by danielfernandez** [comment]
Published! http://www.thymeleaf.org/documentation.html

**Comment by bufferings** [comment]
Thanks a lot!!

**Pull request merged**
